import * as Haptics from 'expo-haptics';
import React,{createContext,useCallback,useContext,useEffect,useMemo,useState} from 'react';
import { achievements,initialProfile,initialProgress,initialSettings } from '../data/content';
import { storage } from '../services/storage';
import { AppState, Question, QuestionStats } from '../types';
interface Context extends AppState { answer:(q:Question,correct:boolean)=>void; setSetting:(key:keyof AppState['settings'],value:boolean)=>void; completeTable:(table:number)=>void; setName:(name:string)=>void }
const AppContext=createContext<Context|null>(null);
const today=()=>new Date().toISOString().slice(0,10);
export function AppProvider({children}:{children:React.ReactNode}){const [state,setState]=useState<AppState>({profile:initialProfile,progress:initialProgress,settings:initialSettings,stats:{},achievements,hydrated:false});
useEffect(()=>{storage.load().then(data=>setState({...data,hydrated:true}));},[]);
useEffect(()=>{if(!state.hydrated)return; void storage.save('profile',state.profile); void storage.save('progress',state.progress); void storage.save('settings',state.settings); void storage.save('stats',state.stats); void storage.save('achievements',state.achievements)},[state]);
const answer=useCallback((q:Question,isCorrect:boolean)=>setState(s=>{const old=s.stats[q.key]??{question:q.key,a:q.a,b:q.b,attempts:0,correct:0,incorrect:0,streak:0,lastAnswered:'',difficulty:1}; const stat:QuestionStats={...old,attempts:old.attempts+1,correct:old.correct+(isCorrect?1:0),incorrect:old.incorrect+(isCorrect?0:1),streak:isCorrect?old.streak+1:0,lastAnswered:new Date().toISOString(),difficulty:Math.max(1,old.difficulty+(isCorrect?-.3:1))}; const combo=isCorrect?s.profile.currentCombo+1:0; const bonus=combo===10?50:combo===5?25:0; const daily=s.progress.lastPracticeDate===today()?s.progress.dailyStreak:s.progress.lastPracticeDate? s.progress.dailyStreak+1:1; const dailyBonus=s.progress.lastPracticeDate===today()?0:50; const progress={...s.progress,totalQuestions:s.progress.totalQuestions+1,correctAnswers:s.progress.correctAnswers+(isCorrect?1:0),incorrectAnswers:s.progress.incorrectAnswers+(isCorrect?0:1),bestCombo:Math.max(s.progress.bestCombo,combo),dailyStreak:daily,lastPracticeDate:today()}; const unlock=(id:string,condition:boolean)=>condition?s.achievements.map(a=>a.id===id&&!a.unlockedAt?{...a,unlockedAt:new Date().toISOString()}:a):s.achievements; let a=unlock('first',progress.correctAnswers>=1); a=unlock('ten',progress.correctAnswers>=10); a=unlock('combo10',combo>=10); a=unlock('combo50',combo>=50); return {...s,stats:{...s.stats,[q.key]:stat},progress,profile:{...s.profile,stars:s.profile.stars+(isCorrect?10+bonus+dailyBonus:0),coins:s.profile.coins+(isCorrect?1:0),currentCombo:combo},achievements:a};}),[]);
const value=useMemo<Context>(()=>({...state,answer,setSetting:(key,value)=>setState(s=>({...s,settings:{...s.settings,[key]:value}})),setName:name=>setState(s=>({...s,profile:{...s.profile,name}})),completeTable:table=>setState(s=>{const studied=[...new Set([...s.progress.studiedTables,table])]; let a=s.achievements.map(x=>x.id==='student'&&!x.unlockedAt?{...x,unlockedAt:new Date().toISOString()}:x); if(studied.length===10)a=a.map(x=>x.id==='master'&&!x.unlockedAt?{...x,unlockedAt:new Date().toISOString()}:x); return {...s,profile:{...s.profile,stars:s.profile.stars+100},progress:{...s.progress,studiedTables:studied,tableProgress:{...s.progress.tableProgress,[table]:100}},achievements:a}})}),[state,answer]); return <AppContext.Provider value={value}>{children}</AppContext.Provider>}
export const useApp=()=>{const ctx=useContext(AppContext);if(!ctx)throw new Error('AppProvider missing');return ctx};
